version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: whatsapp-digest-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=unforgettable_evil_bot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d unforgettable_evil_bot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - whatsapp-network

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: whatsapp-digest-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - whatsapp-network

  # Main application
  whatsapp-digest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-digest-app
    restart: unless-stopped
    ports:
      - "9876:9876"  # FastAPI
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/unforgettable_evil_bot
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - PYTHON_BACKEND_URL=http://127.0.0.1:9876
    volumes:
      - ./whatsapp_sessions:/app/whatsapp_sessions
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9876/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - whatsapp-network

volumes:
  postgres-data:
  redis-data:

networks:
  whatsapp-network:
    driver: bridge
