version: '3.8'

services:
  # Main application optimized for Coolify
  whatsapp-digest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-digest-app
    restart: unless-stopped
    ports:
      - "9876:9876"  # FastAPI
    environment:
      # Database - Coolify will provide these
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}

      # Required API keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

      # Core application settings
      - PYTHON_BACKEND_URL=http://127.0.0.1:9876
      - DEBUG=false
      - LOG_LEVEL=INFO

      # Performance optimization
      - MAX_WORKERS=8
      - DB_POOL_SIZE=15
      - DB_MAX_OVERFLOW=25

      # Cleanup settings
      - CLEANUP_OLD_MESSAGES_DAYS=30
      - CLEANUP_OLD_SYSTEM_LOGS_DAYS=7

      # Repository optimization
      - USE_OPTIMIZED_REPOSITORIES=true

      # OpenAI settings
      - OPENAI_MODEL=gpt-4o-mini
      - OPENAI_MAX_TOKENS=1000
      - OPENAI_TEMPERATURE=0.3

    volumes:
      - whatsapp-sessions:/app/whatsapp_sessions
      - app-logs:/app/logs

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9876/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    # Simplified resource limits
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '0.8'
        reservations:
          memory: 512M
          cpus: '0.3'

volumes:
  whatsapp-sessions:
    driver: local
  app-logs:
    driver: local
