"""add_openai_metrics_table

Revision ID: 2bffd4260324
Revises: b2419b8e0ca6
Create Date: 2025-08-24 00:13:19.076854

"""
from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "2bffd4260324"
down_revision: Union[str, None] = "b2419b8e0ca6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_digest_logs_created_at", table_name="digest_logs")
    op.drop_index("idx_digest_logs_user_created", table_name="digest_logs")
    op.drop_index("idx_monitored_chats_chat_id", table_name="monitored_chats")
    op.drop_index("idx_monitored_chats_user_active", table_name="monitored_chats")
    op.drop_index("idx_system_logs_created_at", table_name="system_logs")
    op.drop_index("idx_system_logs_user_event", table_name="system_logs")
    op.drop_index("idx_users_active_connected", table_name="users")
    op.drop_index("idx_users_whatsapp_connected", table_name="users")
    op.drop_index(
        "idx_whatsapp_messages_chat_timestamp", table_name="whatsapp_messages"
    )
    op.drop_index("idx_whatsapp_messages_importance", table_name="whatsapp_messages")
    op.drop_index("idx_whatsapp_messages_processed", table_name="whatsapp_messages")
    op.drop_index(
        "idx_whatsapp_messages_processed_importance", table_name="whatsapp_messages"
    )
    op.drop_index("idx_whatsapp_messages_timestamp", table_name="whatsapp_messages")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_whatsapp_messages_timestamp",
        "whatsapp_messages",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_whatsapp_messages_processed_importance",
        "whatsapp_messages",
        ["is_processed", "importance_score"],
        unique=False,
    )
    op.create_index(
        "idx_whatsapp_messages_processed",
        "whatsapp_messages",
        ["is_processed"],
        unique=False,
    )
    op.create_index(
        "idx_whatsapp_messages_importance",
        "whatsapp_messages",
        ["importance_score"],
        unique=False,
    )
    op.create_index(
        "idx_whatsapp_messages_chat_timestamp",
        "whatsapp_messages",
        ["chat_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_users_whatsapp_connected", "users", ["whatsapp_connected"], unique=False
    )
    op.create_index(
        "idx_users_active_connected",
        "users",
        ["is_active", "whatsapp_connected"],
        unique=False,
    )
    op.create_index(
        "idx_system_logs_user_event",
        "system_logs",
        ["user_id", "event_type"],
        unique=False,
    )
    op.create_index(
        "idx_system_logs_created_at", "system_logs", ["created_at"], unique=False
    )
    op.create_index(
        "idx_monitored_chats_user_active",
        "monitored_chats",
        ["user_id", "is_active"],
        unique=False,
    )
    op.create_index(
        "idx_monitored_chats_chat_id", "monitored_chats", ["chat_id"], unique=False
    )
    op.create_index(
        "idx_digest_logs_user_created",
        "digest_logs",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_digest_logs_created_at", "digest_logs", ["created_at"], unique=False
    )
    # ### end Alembic commands ###
