"""add_resource_savings_table

Revision ID: 3e7da6056948
Revises: 2bffd4260324
Create Date: 2025-08-24 00:30:25.147521

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "3e7da6056948"
down_revision: Union[str, None] = "b2419b8e0ca6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
