"""add_whatsapp_monitoring_fields

Revision ID: 49d95ee9b45d
Revises: 21317db18350
Create Date: 2025-08-18 10:03:17.313159

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "49d95ee9b45d"
down_revision: Union[str, None] = "21317db18350"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("digest_logs", sa.Column("telegram_error", sa.Text(), nullable=True))
    op.add_column(
        "digest_logs", sa.Column("generation_time_seconds", sa.Float(), nullable=True)
    )
    op.alter_column(
        "digest_logs", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "digest_logs", "digest_content", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "digest_logs", "message_count", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("digest_logs", "digest_content_ru")
    op.add_column(
        "monitored_chats", sa.Column("auto_added", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "monitored_chats", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    op.alter_column(
        "monitored_chats", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "monitored_chats", "chat_id", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "monitored_chats", "chat_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "monitored_chats", "chat_type", existing_type=sa.VARCHAR(), nullable=False
    )
    op.add_column(
        "users", sa.Column("whatsapp_last_seen", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "users", sa.Column("whatsapp_auto_reconnect", sa.Boolean(), nullable=True)
    )
    op.add_column("users", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.add_column(
        "whatsapp_messages", sa.Column("has_media", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "whatsapp_messages", sa.Column("ai_analyzed", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "whatsapp_messages",
        sa.Column("processing_attempts", sa.Integer(), nullable=True),
    )
    op.add_column(
        "whatsapp_messages", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    op.alter_column(
        "whatsapp_messages", "chat_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "whatsapp_messages", "message_id", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "whatsapp_messages", "sender", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "whatsapp_messages", "content", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "whatsapp_messages", "timestamp", existing_type=sa.DATETIME(), nullable=False
    )
    op.create_unique_constraint(None, "whatsapp_messages", ["message_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "whatsapp_messages", type_="unique")
    op.alter_column(
        "whatsapp_messages", "timestamp", existing_type=sa.DATETIME(), nullable=True
    )
    op.alter_column(
        "whatsapp_messages", "content", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "whatsapp_messages", "sender", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "whatsapp_messages", "message_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "whatsapp_messages", "chat_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("whatsapp_messages", "created_at")
    op.drop_column("whatsapp_messages", "processing_attempts")
    op.drop_column("whatsapp_messages", "ai_analyzed")
    op.drop_column("whatsapp_messages", "has_media")
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("users", "updated_at")
    op.drop_column("users", "whatsapp_auto_reconnect")
    op.drop_column("users", "whatsapp_last_seen")
    op.alter_column(
        "monitored_chats", "chat_type", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "monitored_chats", "chat_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "monitored_chats", "chat_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "monitored_chats", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("monitored_chats", "updated_at")
    op.drop_column("monitored_chats", "auto_added")
    op.add_column(
        "digest_logs", sa.Column("digest_content_ru", sa.TEXT(), nullable=True)
    )
    op.alter_column(
        "digest_logs", "message_count", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "digest_logs", "digest_content", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column("digest_logs", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("digest_logs", "generation_time_seconds")
    op.drop_column("digest_logs", "telegram_error")
    # ### end Alembic commands ###
