"""add_custom_name_to_monitored_chats

Revision ID: 4fb32425e140
Revises: 3e7da6056948
Create Date: 2025-09-02 13:50:52.961451

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4fb32425e140"
down_revision: Union[str, None] = "3e7da6056948"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add custom_name column for alternative chat names
    op.add_column(
        "monitored_chats",
        sa.Column("custom_name", sa.String(length=200), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_whatsapp_messages_processed"),
        "whatsapp_messages",
        ["is_processed"],
        unique=False,
    )
    op.create_index(
        op.f("idx_whatsapp_messages_importance"),
        "whatsapp_messages",
        ["importance_score"],
        unique=False,
    )
    op.create_index(
        op.f("idx_whatsapp_messages_chat_timestamp"),
        "whatsapp_messages",
        ["chat_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("idx_whatsapp_messages_ai_analyzed"),
        "whatsapp_messages",
        ["ai_analyzed"],
        unique=False,
    )
    op.create_index(
        op.f("idx_users_whatsapp_last_seen"),
        "users",
        ["whatsapp_last_seen"],
        unique=False,
    )
    op.create_index(
        op.f("idx_users_whatsapp_connected"),
        "users",
        ["whatsapp_connected"],
        unique=False,
    )
    op.create_index(
        op.f("idx_system_logs_user_event"),
        "system_logs",
        ["user_id", "event_type"],
        unique=False,
    )
    op.create_index(
        op.f("idx_system_logs_severity_created"),
        "system_logs",
        ["severity", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_monitored_chats_user_active"),
        "monitored_chats",
        ["user_id", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("idx_monitored_chats_auto_added"),
        "monitored_chats",
        ["auto_added"],
        unique=False,
    )
    op.drop_column("monitored_chats", "custom_name")
    op.create_index(
        op.f("idx_digest_logs_user_created"),
        "digest_logs",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_digest_logs_telegram_sent"),
        "digest_logs",
        ["telegram_sent"],
        unique=False,
    )
    # ### end Alembic commands ###
